---
- name: playbook for common config tasks
  hosts: all
  tasks:
    - name: latest aptitude installed, cache updated, packages upgraded
      ansible.builtin.apt:
        become: yes
        name: aptitude
        state: latest
        update_cache: yes
        upgrade: safe
    - name: root ssh configuration removed
      ansible.builtin.file:
        become: yes
        path: /root/.ssh 
        state: absent
    - name: root ssh login disabled
      ansible.builtin.lineinfile:
        become: yes
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        
