---
### hostname
- name: hostname reset
  ansible.builtin.hostname:
    name: {{u22_common_hostname}}
- name: hosts file reset
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{u22_common_hostname}} {{u22_domain_info.name | join(' ')}}"    
### apt maintenance & package install
- name: apt cache updated
  ansible.builtin.apt:
    update_cache: yes
- name: select system packages installed/updated
  ansible.builtin.apt:
    name:
      - aptitude
      - systemd-timesyncd
      - unattended-upgrades
      - ufw
    state: latest
### firewall config
- name: firewall rules reset
  community.general.ufw:
    state: reset
- name: ssh allowed but rate-limited by ufw to mitigate ssh brute force attacks
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
- name: ufw enabled and set to deny by default
  community.general.ufw:
    state: enabled
    default: deny
### sshd config
- name: root ssh configuration removed
  notify: restart sshd
  ansible.builtin.file:
    path: /root/.ssh 
    state: absent
- name: root ssh login disabled
  notify: restart sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
### locale config
- name: locale set to en/us
  community.general.locale_gen:
    name: "{{u22_common_locale}}"
    state: present
### time/date config
- name: timezone set to utc
  notify: refresh tzdata
  community.general.timezone:
    name: "{{u22_common_timezone}}"
