---
- name: restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
- name: refresh tzdata
  ansible.builtin.command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
    