---
- name: sshd restart
  ansible.builtin.service:
    name: ssh
    state: restarted
- name: tzdata refresh
  ansible.builtin.command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
    